---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: policy-agent
  labels:
    app: policy-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-agent
  template:
    metadata:
      labels:
        app: policy-agent
    spec:
      serviceAccountName: policy-agent
      imagePullSecrets:
        - name: image-pull-secret
      containers:
        - name: policy-agent
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POLICY_SERVER_URL
              value: {{ .Values.policyServer.address }}
            - name: POLL_INTERVAL
              value: {{ .Values.pollInterval }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: policy-agent
              mountPath: /etc/ssl/certs/policy-agent
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: policy-agent
          secret:
            secretName: {{ required "certificateSecret is a required value" .Values.certificateSecret }}
